### ISSUE TITLE
Cannot download torrents

### ISSUE THREAD

**Issue by ToRvaLDz** [gborri/Sick-Beard#13] opened 2014-10-23 15:27 UTC
Hello,
since few releases I'm finding all the new episodes in state: downloadable but it doesn't download anymore from torrent.

I'm using tntvillage and transmission under windows.

Thank you

```

2014-10-23 17:15:55 INFO     SEARCHQUEUE-DOWNLOADABLE_SEARCH-262980 :: No available episodes found during downloadable search for [House of Cards]
2014-10-23 17:15:55 ERROR    SEARCHQUEUE-DOWNLOADABLE_SEARCH-262980 :: No NZB/Torrent providers found or enabled in the sickbeard config for backlog searches. Please check your settings.
AA
AAKeyError: 
AA    return neededEps[episode]
AA  File "C:\Users\ToRvaLDs\Documents\sick\sickbeard\tvcache.py", line 284, in searchCache
AA    cacheResult = self.cache.searchCache(epObj, manualSearch)
AA  File "C:\Users\ToRvaLDs\Documents\sick\sickbeard\providers\generic.py", line 267, in findSearchResultsDownloadable
AA    searchResults = curProvider.findSearchResultsDownloadable(show, episodes, search_mode, manualSearch)
AA  File "C:\Users\ToRvaLDs\Documents\sick\sickbeard\search.py", line 513, in searchProviders
2014-10-23 17:15:55 ERROR    SEARCHQUEUE-DOWNLOADABLE_SEARCH-262980 :: [TNTVillage] :: Error while searching TNTVillage, skipping: error House of Cards - 2x3 - Capitolo 16
2014-10-23 17:15:54 INFO     SHOWQUEUE-ADD :: Seeing if we need anything from Touch (2012)
2014-10-23 17:15:54 INFO     SHOWQUEUE-ADD :: Launching downloadable search for this show since its episodes are SKIPPED
2014-10-23 17:15:54 INFO     SEARCHQUEUE-DOWNLOADABLE_SEARCH-262980 :: [TNTVillage] :: Found result House.Of.Cards.S02e03-04.720p.Bluray.x264 at http://forum.tntvillage.scambioetico.org/index.php?act=Attach&type=post&id=14037065
2014-10-23 17:15:48 INFO     SEARCHQUEUE-DOWNLOADABLE_SEARCH-262980 :: [TNTVillage] :: Performing episode search for House of Cards
2014-10-23 17:15:48 INFO     SEARCHQUEUE-DOWNLOADABLE_SEARCH-262980 :: Building internal name cache for House of Cards
2014-10-23 17:15:48 INFO     SEARCHQUEUE-DOWNLOADABLE_SEARCH-262980 :: No scene exceptions update needed
2014-10-23 17:15:48 INFO     SEARCHQUEUE-DOWNLOADABLE_SEARCH-262980 :: Beginning downloadable search for [House of Cards]
```

**Comment by gborri** [comment] 2014-10-27 13:56
are you on latest commit?

**Comment by ToRvaLDz** [comment] 2014-10-28 14:44
Yes, also it is a new fresh install because I got the same problem in the old one.

```
SB Version: BRANCH: (ThePirateBay) / COMMIT: (6436226631b4c54e6291524e3c983a3f834ec29f) 
Python Version: 2.7.8 (default, Jun 30 2014, 16:08:48) [MSC v.1500 64 bit (AMD64)]
 Homepage   http://www.sickbeard.com/
 Forums http://sickbeard.com/forums/
 Source https://github.com/gborri/Sick-Beard/
```

**Comment by gborri** [comment] 2014-11-06 21:35
downloadable state means that torrent are available on torrent provider.
I have reproduced the problem but not yet find root cause of the problem.
if try to download manually or set episode to wanted i see that it works.
Try..

**Comment by gborri** [comment] 2014-11-07 13:38
should be fixed. try now.

**Closed as completed by gborri** 2014-11-07 13:38 UTC
